#print('Minha tabuada')
#n = int(input('Digite um numero para ver sua tabuada:'))
#print('-----------')
#print('{} x 1 = {}'.format(n, (n*1)))
#print('{} x 2 = {}'.format(n, (n*2)))
#print('{} x 3 = {}'.format(n, (n*3)))
#print('{} x 4 = {}'.format(n, (n*4)))
#print('{} x 5 = {}'.format(n, (n*5)))
#print('{} x 6 = {}'.format(n, (n*6)))
#print('{} x 7 = {}'.format(n, (n*7)))
#print('{} x 8 = {}'.format(n, (n*8)))
#print('{} x 9 = {}'.format(n, (n*9)))
#print('{} x 10 = {}'.format(n, (n*10)))
#print('-----------')

print('Tabuada feita pelo professor')
num = int(input('Digite um número para ver sua tabuada:'))
print('='*12)
print('{} x {:2} = {}'.format(num, 1, (num*1)))
print('{} x {:2} = {}'.format(num, 2, (num*2)))
print('{} x {:2} = {}'.format(num, 3, (num*3)))
print('{} x {:2} = {}'.format(num, 4, (num*4)))
print('{} x {:2} = {}'.format(num, 5, (num*5)))
print('{} x {:2} = {}'.format(num, 6, (num*6)))
print('{} x {:2} = {}'.format(num, 7, (num*7)))
print('{} x {:2} = {}'.format(num, 8, (num*8)))
print('{} x {:2} = {}'.format(num, 9, (num*9)))
print('{} x {:2} = {}'.format(num, 10, (num*10)))
print('='*12)



