#print('Exercicio 4')
#n1 = input('Digite algo:')
#print('Ele é do tipo:',type(n1))
#print('Ele é numero? ', n1.isnumeric())
#print('Ele é Alfa Numerico? ', n1.isalnum())
#print('Ele é umecimal? ', n1.isdecimal())
#print('Ele é um espaço? ', n1.isspace())
#print('Ele é um titulo? ',n1.istitle())
#print('É somente maiusculo?',n1.isupper())
#print('É inferio?', n1.islower())
#print('É um digito?', n1.isdigit())

print('*' * 50)
print('\033[1;33mNovo Exercicio 4, Analisando variaveis.\033[m')
valor = input('\033[1;34mDigite algo:\033[m')
print('\033[1;34mO tipo primitivo desse valor é:\033[m', type(valor))
print('\033[1;34mSó tem espaços?\033[m', valor.isspace())
print('\033[1;34mÉ um numero?\033[m', valor.isnumeric())
print('\033[1;34mÉ alfabético?\033[m', valor.isalpha())
print('\033[1;34mÉ alfanumérico?\033[m', valor.isalnum())
print('\033[1;34mÉsta em maiúsculas?\033[m', valor.isupper())
print('\033[1;34mÉsta em minusculas?\033[m', valor.islower())
print('\033[1;34mÉsta capitalizada?\033[m', valor.istitle()) #para saber se está usando maiscula e minuscula.
print('*' * 50)
